name: Steam Workshop Upload

on:
  push:
    branches: [ main ]

jobs:
  workshop-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: steam-workshop-upload
      uses: KlimeSE/klime-steam-workshop-upload@main
      with: 
        appid: 244850 # Game's Steam App ID
        itemid: 2961726679 # Your mod's Steam Workshop ID
        path: 'Mod' # Path to your mod's folder from repository root
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
        STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)
